MERGE (c:LexContract {census: "LEXPVM-T-160", name: "Moon Phase Notation", cites: "glossary-master-v4 § ### Moon Phase Notation"})
MERGE (:Person {name: "Swordsman", contract: "Moon Phase Notation"})
MERGE (:Number {name: "Stratum Count", contract: "Moon Phase Notation"})
MERGE (:Number {name: "Active Dimensions", contract: "Moon Phase Notation"})
MERGE (:Text {name: "Phase", contract: "Moon Phase Notation"})
MERGE (:Contract {name: "Blade", contract: "Moon Phase Notation"})
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:MAY_SET {clause: "Show Phase", object: "Active Dimensions"}]->(b)
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:MAY_CERTIFY {clause: "Show Phase", object: "Phase"}]->(b)
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:MAY_CERTIFY {clause: "Reflect All", object: "Phase", condition: "this Blade is Full Moon"}]->(b)
