MERGE (c:LexContract {census: "LEXPVM-T-206", name: "Conditional Promise (b\", cites: "promise-theory-ref-v1-4 § ## Quick Reference: Concept Mappings"})
MERGE (:Person {name: "Promiser", contract: "Conditional Promise (b\"})
MERGE (:Person {name: "Promisee", contract: "Conditional Promise (b\"})
MERGE (:Text {name: "Body", contract: "Conditional Promise (b\"})
MERGE (:Binary {name: "Condition Met", contract: "Conditional Promise (b\"})
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Promisee"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:FIX {clause: "recital", object: "Body"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:MAY_DECLARE {clause: "Observe", object: "Condition Met"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promisee"}) CREATE (a)-[:MAY_SEND {clause: "Keep", object: "Body", condition: "Condition Met is declared"}]->(b)
