MERGE (c:LexContract {census: "LEXPVM-T-078", name: "Ashe", cites: "glossary-master-v4 § ### Ashe"})
MERGE (:Person {name: "Ashe", contract: "Ashe"})
MERGE (:Person {name: "First Person", contract: "Ashe"})
MERGE (:Text {name: "Protection Mirror", contract: "Ashe"})
MERGE (:Text {name: "Scrying Glass", contract: "Ashe"})
MERGE (:Binary {name: "Inversion Discovered", contract: "Ashe"})
MATCH (a {name: "Ashe"}), (b {name: "Ashe"}) CREATE (a)-[:MAY_REGISTER {clause: "Build Mirror", object: "Protection Mirror"}]->(b)
MATCH (a {name: "Ashe"}), (b {name: "Ashe"}) CREATE (a)-[:MAY_DECLARE {clause: "Discover", object: "Inversion Discovered"}]->(b)
MATCH (a {name: "Ashe"}), (b {name: "First Person"}) CREATE (a)-[:MAY_SEND {clause: "Invert", object: "Scrying Glass", condition: "Inversion Discovered is declared"}]->(b)
