MERGE (c:LexContract {census: "LEXPVM-T-016", name: "Conditional Promise (b|c)", cites: "glossary-master-v4 § ### Conditional Promise (b|c) § ### Conditional Promise (b|c)"})
MERGE (:Person {name: "Promiser", contract: "Conditional Promise (b|c)"})
MERGE (:Person {name: "Promisee", contract: "Conditional Promise (b|c)"})
MERGE (:Text {name: "Promise Body", contract: "Conditional Promise (b|c)"})
MERGE (:Binary {name: "Condition Met", contract: "Conditional Promise (b|c)"})
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Promisee"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:FIX {clause: "recital", object: "Promise Body"}]->(b)
MATCH (a {name: "Promisee"}), (b {name: "Promisee"}) CREATE (a)-[:MAY_DECLARE {clause: "Observe Condition", object: "Condition Met"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promisee"}) CREATE (a)-[:MAY_SEND {clause: "Keep Promise", object: "Promise Body", condition: "Condition Met is declared"}]->(b)
