MERGE (c:LexContract {census: "LEXPVM-T-013", name: "Promise (Promise Theory)", cites: "glossary-master-v4 § ### Promise (Promise Theory)"})
MERGE (:Person {name: "Promiser", contract: "Promise (Promise Theory)"})
MERGE (:Person {name: "Promisee", contract: "Promise (Promise Theory)"})
MERGE (:Text {name: "Promise Body", contract: "Promise (Promise Theory)"})
MERGE (:Binary {name: "Kept", contract: "Promise (Promise Theory)"})
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Promisee"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:FIX {clause: "recital", object: "Promise Body"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promisee"}) CREATE (a)-[:MAY_SEND {clause: "Make Promise", object: "Promise Body"}]->(b)
MATCH (a {name: "Promisee"}), (b {name: "Promisee"}) CREATE (a)-[:MAY_DECLARE {clause: "Assess", object: "Kept"}]->(b)
