MERGE (c:LexContract {census: "LEXPVM-T-014", name: "Autonomy Axiom", cites: "glossary-master-v4 § ### Autonomy Axiom § ### Autonomy Axiom"})
MERGE (:Person {name: "First Agent", contract: "Autonomy Axiom"})
MERGE (:Person {name: "Second Agent", contract: "Autonomy Axiom"})
MERGE (:Text {name: "First Behavior", contract: "Autonomy Axiom"})
MERGE (:Text {name: "Second Behavior", contract: "Autonomy Axiom"})
MATCH (a {name: "First Agent"}), (b {name: "First Agent"}) CREATE (a)-[:FIX {clause: "recital", object: "First Behavior"}]->(b)
MATCH (a {name: "Second Agent"}), (b {name: "Second Agent"}) CREATE (a)-[:FIX {clause: "recital", object: "Second Behavior"}]->(b)
MATCH (a {name: "First Agent"}), (b {name: "First Agent"}) CREATE (a)-[:MAY_REGISTER {clause: "First Promise", object: "First Behavior"}]->(b)
MATCH (a {name: "Second Agent"}), (b {name: "Second Agent"}) CREATE (a)-[:MAY_REGISTER {clause: "Second Promise", object: "Second Behavior"}]->(b)
