MERGE (c:LexContract {census: "LEXPVM-T-073", name: "Soulbis", cites: "glossary-master-v4 § ### Soulbis"})
MERGE (:Person {name: "Keeper", contract: "Soulbis"})
MERGE (:Person {name: "Soulbis", contract: "Soulbis"})
MERGE (:Text {name: "Translation", contract: "Soulbis"})
MERGE (:Binary {name: "Spellbook Context", contract: "Soulbis"})
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Soulbis"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:FIX {clause: "recital", object: "Translation"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:MAY_DECLARE {clause: "Contextualize", object: "Spellbook Context"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:MAY_CERTIFY {clause: "Certify Translation", object: "Translation", condition: "Spellbook Context is declared"}]->(b)
