MERGE (c:LexContract {census: "LEXPVM-T-088", name: "Yggdrasil", cites: "glossary-master-v4 § ### Yggdrasil"})
MERGE (:Person {name: "Swordsman", contract: "Yggdrasil"})
MERGE (:Person {name: "First Person", contract: "Yggdrasil"})
MERGE (:Text {name: "Specific Reality", contract: "Yggdrasil"})
MERGE (:Binary {name: "Measurement Taken", contract: "Yggdrasil"})
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:APPOINT {clause: "recital", object: "First Person"}]->(b)
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:FIX {clause: "recital", object: "Specific Reality"}]->(b)
MATCH (a {name: "Swordsman"}), (b {name: "Swordsman"}) CREATE (a)-[:MAY_DECLARE {clause: "Measure", object: "Measurement Taken"}]->(b)
MATCH (a {name: "Swordsman"}), (b {name: "First Person"}) CREATE (a)-[:MAY_SEND {clause: "Collapse", object: "Specific Reality", condition: "Measurement Taken is declared"}]->(b)
