MERGE (c:LexContract {census: "LEXPVM-T-179", name: "The 42 → 64 bridge", cites: "glossary-master-v4 § ### 23.6 The 42 → 64 bridge"})
MERGE (:Person {name: "First Person", contract: "The 42 → 64 bridge"})
MERGE (:Number {name: "Vertex Count", contract: "The 42 → 64 bridge"})
MERGE (:Number {name: "Primary Count", contract: "The 42 → 64 bridge"})
MERGE (:Number {name: "Attachment Slots", contract: "The 42 → 64 bridge"})
MERGE (:Text {name: "Attachment Record", contract: "The 42 → 64 bridge"})
MERGE (:Contract {name: "Lattice", contract: "The 42 → 64 bridge"})
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:FIX {clause: "recital", object: "Attachment Record"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_REGISTER {clause: "Attach", object: "Attachment Record", condition: "this Lattice is Open Slotted"}]->(b)
