MERGE (c:LexContract {census: "LEXPVM-T-074", name: "Soulbae", cites: "glossary-master-v4 § ### Soulbae"})
MERGE (:Person {name: "Keeper", contract: "Soulbae"})
MERGE (:Person {name: "Soulbae", contract: "Soulbae"})
MERGE (:Text {name: "Translation", contract: "Soulbae"})
MERGE (:Binary {name: "Spellbook Context", contract: "Soulbae"})
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Soulbae"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:FIX {clause: "recital", object: "Translation"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:MAY_DECLARE {clause: "Contextualize", object: "Spellbook Context"}]->(b)
MATCH (a {name: "Keeper"}), (b {name: "Keeper"}) CREATE (a)-[:MAY_CERTIFY {clause: "Certify Translation", object: "Translation", condition: "Spellbook Context is declared"}]->(b)
