MERGE (c:LexContract {census: "LEXPVM-T-127", name: "Behavioural Density (ρ)", cites: "glossary-master-v4 § ### Behavioural Density (ρ)"})
MERGE (:Person {name: "First Person", contract: "Behavioural Density (ρ)"})
MERGE (:Number {name: "Lap Count", contract: "Behavioural Density (ρ)"})
MERGE (:Number {name: "Shallow Count", contract: "Behavioural Density (ρ)"})
MERGE (:Data {name: "Trajectory", contract: "Behavioural Density (ρ)"})
MERGE (:Text {name: "Reconstruction Resistance", contract: "Behavioural Density (ρ)"})
MERGE (:Contract {name: "Blade", contract: "Behavioural Density (ρ)"})
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:FIX {clause: "recital", object: "Trajectory"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_CERTIFY {clause: "Resist", object: "Reconstruction Resistance", condition: "this Blade is Dense"}]->(b)
