MERGE (c:LexContract {census: "LEXPVM-T-023", name: "Scope", cites: "glossary-master-v4 § ### Scope § ### Scope"})
MERGE (:Person {name: "Promiser", contract: "Scope"})
MERGE (:Person {name: "Insider", contract: "Scope"})
MERGE (:Person {name: "Outsider", contract: "Scope"})
MERGE (:Text {name: "Promise Body", contract: "Scope"})
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Insider"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Outsider"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Promiser"}) CREATE (a)-[:FIX {clause: "recital", object: "Promise Body"}]->(b)
MATCH (a {name: "Promiser"}), (b {name: "Insider"}) CREATE (a)-[:MAY_SEND {clause: "Share Within Scope", object: "Promise Body"}]->(b)
