MERGE (c:LexContract {census: "LEXPVM-T-069", name: "Spell", cites: "glossary-master-v4 § ### Spell"})
MERGE (:Person {name: "First Person", contract: "Spell"})
MERGE (:Text {name: "Notation", contract: "Spell"})
MERGE (:Number {name: "Compression Ratio", contract: "Spell"})
MERGE (:Contract {name: "Grimoire", contract: "Spell"})
MERGE (:Binary {name: "Spell Cast", contract: "Spell"})
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:SET {clause: "recital", object: "Compression Ratio"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_REGISTER {clause: "Cast", object: "Notation", condition: "this Grimoire is Dense Spell"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_DECLARE {clause: "Cast", object: "Spell Cast", condition: "this Grimoire is Dense Spell"}]->(b)
