MERGE (c:LexContract {census: "LEXPVM-T-182", name: "The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)", cites: "glossary-master-v4 § ### 24.1 The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)"})
MERGE (:Person {name: "Cast", contract: "The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)"})
MERGE (:Person {name: "Archivist", contract: "The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)"})
MERGE (:Text {name: "Higher Seat", contract: "The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)"})
MERGE (:Text {name: "Cast Entry", contract: "The Tower (v1.7.0 · 8th spatial-anatomy element of the City of Mages)"})
MATCH (a {name: "Cast"}), (b {name: "Cast"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Archivist"}]->(b)
MATCH (a {name: "Cast"}), (b {name: "Cast"}) CREATE (a)-[:FIX {clause: "recital", object: "Cast Entry"}]->(b)
MATCH (a {name: "Cast"}), (b {name: "Cast"}) CREATE (a)-[:MAY_REGISTER {clause: "Recognize", object: "Higher Seat"}]->(b)
MATCH (a {name: "Cast"}), (b {name: "Cast"}) CREATE (a)-[:MAY_CERTIFY {clause: "Recognize", object: "Cast Entry"}]->(b)
