MERGE (c:LexContract {census: "LEXPVM-T-113", name: "Generator (BRAID) (V5)", cites: "glossary-master-v4 § ### Generator (BRAID) (V5)"})
MERGE (:Person {name: "Generator", contract: "Generator (BRAID) (V5)"})
MERGE (:Person {name: "Solver", contract: "Generator (BRAID) (V5)"})
MERGE (:Text {name: "Traversal Structure", contract: "Generator (BRAID) (V5)"})
MERGE (:Text {name: "Reasoning Graph", contract: "Generator (BRAID) (V5)"})
MERGE (:Contract {name: "Braid", contract: "Generator (BRAID) (V5)"})
MATCH (a {name: "Generator"}), (b {name: "Generator"}) CREATE (a)-[:MAY_FIX {clause: "Plan", object: "Traversal Structure"}]->(b)
MATCH (a {name: "Generator"}), (b {name: "Generator"}) CREATE (a)-[:MAY_CERTIFY {clause: "Plan", object: "Reasoning Graph"}]->(b)
MATCH (a {name: "Generator"}), (b {name: "Solver"}) CREATE (a)-[:MAY_SEND {clause: "Deliver", object: "Reasoning Graph"}]->(b)
