MERGE (c:LexContract {census: "LEXPVM-T-056", name: "ERC-8004", cites: "glossary-master-v4 § ### ERC-8004"})
MERGE (:Person {name: "First Person", contract: "ERC-8004"})
MERGE (:Person {name: "Agent", contract: "ERC-8004"})
MERGE (:Data {name: "Identity Record", contract: "ERC-8004"})
MERGE (:Binary {name: "Identity Verified", contract: "ERC-8004"})
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:APPOINT {clause: "recital", object: "Agent"}]->(b)
MATCH (a {name: "Agent"}), (b {name: "Agent"}) CREATE (a)-[:MAY_REGISTER {clause: "Attest", object: "Identity Record"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_DECLARE {clause: "Verify", object: "Identity Verified"}]->(b)
MATCH (a {name: "First Person"}), (b {name: "First Person"}) CREATE (a)-[:MAY_CERTIFY {clause: "Recognize", object: "Identity Record", condition: "Identity Verified is declared"}]->(b)
